---

- hosts: "{{ hosts_group }}"
  become: yes
  vars:
    hosts_group: "localhost"

  tasks:
    - name: run whoami and register to shell_result1
      become_method: su
      become_user: robin
      shell: whoami&&echo $PATH
      register: shell_result1
     
    - name: print the shell_result1
      debug:
        msg: "shell_result1 is {{ shell_result1.stdout_lines  }}"

    - name: run the command and save result to shell_result2
      shell: sudo -i -u robin docker ps -a
      register: shell_result2

    - name: print the shell_result2
      debug:
        msg: "shell_result2 is {{ shell_result2.stdout_lines  }}"

