---

- hosts: "{{ hosts_group }}"
  remote_user: root
  vars:
    name1: robin
    hosts_group: "localhost"
    date1: 2020-02-02
    age1: 21
    age2: '21'
    married: True
    married2: true
    married3: 'true'
    names2: [robin,joseph]
    workspaces: [appvol,appvol02]
    info1: [ {"workspace":appvol,"instance":JBD1} ]
    info2: [ {"workspace":appvol02,"instance":JBD2} ]
    log1: 'hello\nworld\nihao\nzhongguo'

  tasks:
    - name: get the workspaces
      shell: "df -h|grep -v Mounted|awk '{print $6}'"
      args:
        chdir: /apps/ansible-test/
      register: workss
    
    - name: register vars
      set_fact:
        my_lists: []
   
 
    - name: register vars with workss name
      set_fact:
         my_lists: "{{ my_lists + [ item] }}"
      with_lines: "echo -en '{{workss.stdout}}'"
       
    - debug:
       msg: "{{ my_lists }}"    
    
    - name: get the instance name from every workss
      shell: "ls {{ item }}"
      register: instances
      with_items: "{{ my_lists }}"

    - name: echo instances
      debug:
        msg: "{{ item.item }} {{ item.stdout }}"
      with_items: "{{ instances.results }}"

    #- name: merge 2 lists
    #  set_fact:
    #    my_lists: "{{ my_lists +  info1 + info2 }}"
    
    #- debug:
    #    msg: "{{ item }}"
    #  with_items: "{{ my_lists }}"
