---

- hosts: "{{ hosts_group }}"
  become: yes
  become_method: sudo
  become_user: root  

  vars:
    ansible_ssh_user: robin
    name1: root
    hosts_group: "gcp"
    date1: 2020-02-02
    age1: 21
    age2: '21'
    married: True
    married2: true
    married3: 'true'
    path: '$PATH'

  tasks:
    - name: pip insall web.py
      shell: "export PATH=$PATH:/usr/bin/:/usr/local/bin/;pip install web.py"
      async: 20
      poll: 10
      register: rst1

    - name: echo rst1
      debug:
        msg: "{{ rst1 }}"

    - name: pip insall web.py
      shell: "echo $PATH"
      async: 200
      poll: 0
      register: pip_install_status

    - name: 'YUM - check on fire and forget task'
      async_status: jid={{ pip_install_status.ansible_job_id }}
      register: job_result
      until: job_result.finished
      retries: 30
   
    - name: echo teh result2
      debug:
        msg: "{{job_result }}"
   
    - name: rewrite the age2
      shell: "age2=22"

    - name: echo age2
      debug:
        msg: "age2 {{age2}}"
