---

- hosts: "{{ hosts_group }}"
  remote_user: root
  vars:
    hosts_group: "localhost"
    env_name_alias: cn

  roles:
    - ansible-include

- name: include the playbook
  import_playbook: ansible-include-subplay.yml
